### ISSUE TITLE
Add option `ack_on_failure`

### ISSUE THREAD

**Issue by msaraiva** [dashbitco/broadway_sqs#17]

**Comment by josevalim** [comment]
We should mirror the configurations for RabbitMQ: on_success and on_failure and our possible values will be `:ack | :noop`.

**Comment by wojtekmach** [comment]
@josevalim @mcrumm on broadway_sqs we have `:ack | :noop`, on cloud_pubsub we have `:ack | :ignore`, which option should we standardise on? I'm happy to make the change in the appropriate connector.

**Comment by mcrumm** [comment]
@wojtekmach Personally, I like `:noop`. Ignore could _potentially_ be construed for dropping the message, whereas noop is explicit about doing nothing.

**Comment by wojtekmach** [comment]
I assume José wants :noop too since he proposed it :) Ill send a patch to cloud_pub_sub tomorrow.
