### ISSUE TITLE
Error reporting/handling? (Acknowledgement silent errors!)

### ISSUE THREAD

**Issue by igorescobar** [dashbitco/broadway_sqs#42]
Hey guys,

First of all. Thanks a lot for putting so much work into this and making it available for us. 

What happened with us is that we deployed to production Broadway + Broadway SQS and we noticed that the messages just wasn't being "acknowledged" on the AWS side so all messages were coming through but they weren't being deleted so they just stayed as "in flight" and then appeared again to be processed and eventually went to DLQ.

We spent *many many* hours trying to understand what was wrong because since there was no errors, exceptions of any sort on our logs... everything seemed to be just fine. 

Naturally, we suspected that something was wrong with our implementation, read and re-read docs and examples everywhere, checked networking, CPU resources, everything! But in the end the AWS ACCESS KEY used to connect to SQS just didn't have enough permissions to "delete" messages or delete messages in batch (I didn't created the API key myself). As always the error was *really* stupid but since it wasn't obvious straight away we spent many hours looking at the wrong places.

My goal with this issue is at first to document what happened to us but also let you know that these silent errors can also be very tricky. Would be nice to have on the docs or to have a option on the client like a debug mode so we could have more verbose information regarding those "silent" errors during desperate times.

Thanks!

**Comment by josevalim** [comment]
Good find, thanks for the reporting. We should check the response of all SQS commands or use the request! variant.

**Comment by josevalim** [comment]
@mcrumm pinging you to double check if we have a similar issue on cloud_pub_sub.

**Comment by mcrumm** [comment]
@josevalim thanks for the ping! I think the Pub/Sub logs any failed request, but I'll double-check
