### ISSUE TITLE
Document wildcard support for `message_attribute_names`

### ISSUE THREAD

**Issue by tjsousa** [dashbitco/broadway_sqs#47]
[According to AWS documentation there is support for wildcards](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html) when specifying which message attributes to retrieve.

For testing purposes we use https://github.com/softwaremill/elasticmq which doesn't seem to support the `All` parameter but does indeed support `.*` I've tried specifying it as `message_attribute_names` and it works as expected. Would it be useful to add it to the documentation?

```elixir
producer: [
  module: {BroadwaySQS.Producer,
    queue_url: "https://sqs.amazonaws.com/0000000000/my_queue",
    message_attribute_names: [".*"],
  }
]
```

**Comment by josevalim** [comment]
Please send a PR!

**Comment by tjsousa** [comment]
Cool, here's the PR ☝️
