### ISSUE TITLE
Dependency on ex_aws_sqs

### ISSUE THREAD

**Issue by justincjohnson** [dashbitco/broadway_sqs#57]
Hi 👋

**Background**
As you are aware, [recently](https://elixirforum.com/t/maintainer-wanted-exaws/31731) the maintainer of `ex_aws` stepped away from the project and expressed some concerns with how the library is written.  I understand that another maintainer has stepped up to take over the project, which is great and appreciated.

This lead to some discussion about the possible use of [aws_elixir](https://github.com/aws-beam/aws-elixir) under the [aws-beam](https://github.com/aws-beam) GitHub organization as an alternative, which uses [aws-codegen](https://github.com/aws-beam/aws-codegen) to generate client code from the AWS Go SDK specs.  Manually written code is still necessary, but the codegen lightens the maintenance burden considerably.

These events, plus the need for me to find an AWS library that supports IMDSv2 (See [here](https://github.com/ex-aws/ex_aws/pull/739) and [here](https://github.com/aws-beam/aws_credentials/issues/13) for some movement on that) has lead me to explore which library I want to use going forward, as well as to think through ways to ensure that my code is more isolated from changes to our external dependencies.  It seems ideal if my code can wrap external dependencies and ensure that they conform to a specific behaviour, enabling me to swap out dependencies in the future with limited impact.

**Proposal**
With all of that as background, has there been any consideration to possibly removing the dependency on `ex_aws_sqs` and allowing the choice of AWS SQS client to be swapped out by consumers of the library?  I already have local adapters for an SQS behaviour that I use for dev, test and prod to wrap up some of my direct ExAws calls, but I need to extend this into our dependencies like Broadway SQS as well.

For reference, it looks like these are the current dependencies on `ex_aws` and `ex_aws_sqs` on master.

```
ExAws.SQS.send_message/2
ExAws.SQS.request/2
ExAws.SQS.request!/2
ExAws.SQS.create_queue/1
ExAws.SQS.receive_message/2
ExAws.SQS.delete_message_batch/2
ExAws.Request.HttpClient behaviour used in tests
```

Does this proposal sound reasonable to you?  And if so, would you like help implementing the changes?  Any input or guidance is greatly appreciated.

Thanks for your time and for an excellent project!

**Comment by josevalim** [comment]
We already have a behaviour for the SQS client, so you can try to plug that in. You don't have to worry about things like delete_message_batch because you can setup your own acknowledger when you receive messages. So I would recommend giving that a try and letting us know how it goes! 

> Thanks for your time and for an excellent project!

:heart:

**Comment by justincjohnson** [comment]
Ah, brilliant.  I see that I'm already implementing both behaviours for dev, so I just need to do the same for prod.  🤦🏻   I'm slowly learning the beauty of behaviours.
