### ISSUE TITLE
Process Single Batch of Messages in Parallel

### ISSUE THREAD

**Issue by austinarbor-wk** [dashbitco/broadway_sqs#66]
Is there a way to send each message received in a batch to a different processor? From my local testing, it seems all messages received in a batch always go to the same processor (pid). I would expect that if I have producer concurrency = 1, and processor concurrency = 10, if I receive 10 messages each message would get processed in parallel. Instead, each message consumed in the batch is processed synchronously by the same processor. My config:

```elixir
[
      producer: [
        module: {
          BroadwaySQS.Producer,
          queue_url: "http://example.com/myQueue",
          wait_time_seconds: 20,
          max_number_of_messages: 10,
          receive_interval: 100,
        },
        concurrency: 1
      ],
      processors: [
        default: [
          concurrency: 10
        ]
      ]
    ]
```

It seems like the only way to do what I am looking for is to set `max_number_of_messages` to `1`, which will come with significant performance and cost implications.

Am I missing anything? 

Thanks!

**Comment by austinarbor-wk** [comment]
I did some more experimentation, and if I add
```elixir
batchers: [
        default: [batch_size: 1, concurrency: 10]
      ]
```
This seems to accomplish what I want. However, it seems a little bit like a hacky approach and I'm wondering if there is a better way?

**Comment by josevalim** [comment]
The amount of items you receive to process is controlled by `max_demand`, which defaults to 10. You can set `max_demand` to 1 and then each processor receives at most one entry.

**Comment by austinarbor-wk** [comment]
@josevalim thanks! I forgot reading about that configuration option
