### ISSUE TITLE
SQS Partitioning Unexpected Behavior

### ISSUE THREAD

**Issue by austinarbor** [dashbitco/broadway_sqs#69]
Hello,
When using partitioning on a FIFO queue on SQS, I am seeing some unexpected behavior. My broadway config is:
```elixir
[
      producer: [
        module: {
          MyModule,
          queue_url: "http://my/queue/,
          on_failure: :ack,
          wait_time_seconds: 20,
          max_number_of_messages: 10,
          receive_interval: 10,
          attribute_names: :all,
          config: my_aws_config
        },
        concurrency: 1
      ],
      processors: [
        default: [
          concurrency: 75,
          max_demand: 1
          partition_by: &partition/1 #see below
        ]
      ],
      batchers: [
        default: [
          batch_size: 100, 
          batch_timeout: 300,
          concurrency: 3
        ]
      ]
    ]
```

The partition function set on the processors is:
```elixir
def partition(%Message{
        metadata: %{
          attributes: %{
            "message_group_id" => message_group_id
          }
        }
      }) do
    :erlang.phash2(message_group_id)
  end
```

When running the pipeline like this, the observed behavior is:
1. `N` available messages are pulled down from SQS (all with the same message group id). Assume the queue is empty after this poll
2. The partition function is run immediately on all of the messages
3. The first message is sent to `handle_message()`
4. The first message is sent to `handle_batch()` and ack'd / deleted
5. We wait `wait_time_seconds`
6. The second message is processed starting at step 3 and the loop continues

From the behavior, it seems like in step 5 we are sending a poll request to SQS for more messages. Since none exist on the queue, it is waiting for the full duration of `wait_time_seconds`.  In my opinion, since we already have messages ready to be processed from the previous poll, we shouldn't need to send a request to SQS for more messages yet. To counteract this behavior, I have set `max_demand: 10` on the processor config and it seems to fix the problem as far as I can tell.  Even though a fix exists, I think the existing behavior is confusing and most likely not what a user expects to happen. Is there something wrong with my config that I should be changing instead?

Thanks!

**Comment by josevalim** [comment]
Can you perhaps reproduce This in our test suit? It will make it much easier for us to debug and solve it. Thanks!

**Comment by josevalim** [comment]
Wrong button, sorry!

**Comment by austinarbor** [comment]
@josevalim I've created a reproducer project for you here: https://github.com/austinarbor/broadway-sqs-issue Instructions are in the README, let me know if you have any questions!

**Comment by austinarbor** [comment]
Hi @josevalim , any luck reproducing this?  Thanks!

**Comment by josevalim** [comment]
The issue is here:

```
          concurrency: 75,
          max_demand: 1,
```

We expect our partitions to be even. So we will only progress once all partitions are ready to ask for more. The combination of a high number of concurrency and max_demand 1 makes it really hard to progress. Even setting max_demand to 10 will help a bit because you can ask for more mid way (when you processed 5).

**Comment by austinarbor** [comment]
@josevalim I think you misunderstood - the messages from sqs have _already been fetched_ by Broadway, but it is still waiting a full polling interval to send them to the consumers. Shouldn't it send the messages it already has locally to the consumers before requesting more from SQS? 

Forgive me but don't fully understand your configuration comment - it seems like you are saying our configuration is suboptimal.  We want all messages for the same group id processed synchronously, but otherwise we don't care. At most we want 75 messages being processed in parallel. It seemed like the only way to achieve that was through hashing the group id in a partition function. Based on documentation it seems if we set a high demand we may request too many messages from sqs, and if we have a low number of consumers then messages will block each other. Is there a better way of achieving what we want to do?

Thanks

**Comment by josevalim** [comment]
Here is what is happening. You have 75 processors. However, those 75 messages are not evenly distributed across all partitions. This means partition 13 may get 3 messages. However, `max_demand` says they can only have 1. This means partition 13 gets one message and it will only get the other two once all other partitions consume at least 1.

For your needs, `[concurrency: 7, max_demand: 10]` will do a much better job.
