### ISSUE TITLE
Tests failing on updated nimble_options version

### ISSUE THREAD

**Issue by wkirschbaum** [dashbitco/broadway_sqs#76]
When running `mix deps.update --all` on this project and then `mix test` 2 new tests are failing. 

```
  1) test prepare_for_start/2 validation when the queue url is not present (BroadwaySQS.BroadwaySQS.ProducerTest)
     test/broadway_sqs/producer_test.exs:89
     Wrong message for ArgumentError
     expected:
       "invalid configuration given to SQSBroadway.prepare_for_start/2, required option :queue_url not found, received options: []"
     actual:
       "invalid configuration given to SQSBroadway.prepare_for_start/2, required :queue_url option not found, received options: []"
     code: assert_raise(ArgumentError, message, fn ->
     stacktrace:
       test/broadway_sqs/producer_test.exs:95: (test)
```

This appears to be related to the allowed mime version in hackney. 

Maybe this is not an issue, but if a project is using this package then the tests would effectively fail when the packages are updated?

I am a little paranoid as we want to start using this library.

**Comment by josevalim** [comment]
It is rather `nimble_options` that was updated. It changed how the error messages look like, it doesn't seem to have an issue with its actual behaviour. PRs welcome.
